version: '3.9'

services:
  wordpress:
    image: webdevops/php-nginx:8.2
    container_name: wordpress-app
    volumes:
      - ./wordpress:/app
    ports:
      - "8080:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=256M
    depends_on:
      - db

  db:
    image: mariadb
    container_name: wordpress-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

